settings:
  database:
    name: test
    dbType: mysql
    host: 192.168.8.105
    username: root
    password: BVYRDR2Z7X
    port: 3306
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: false


